BETA = 1e-3
GAMMA = 0.99
EPSILON = 0.2
LAMBDA = 0.95

TIME_HORIZON = 5
N_EPISODES = 100_000
ENCODING_SCHEME = "PepBERT-large"

BUFFER_SIZE = 2048 * TIME_HORIZON
BATCH_SIZE = 128
N_EPOCHS = 4

AGENTS_HIDDEN_DIM = 256
AGENTS_DROPOUT_RATE = 0.1
AGENTS_LR = 2e-5
AGENTS_WEIGHT_DECAY = 1e-2
AGENTS_LR_STEP_SIZE = 3
AGENTS_LR_GAMMA = 0.7

N_PARALLELS = 200
RANDOM_SEED = 3407
CHECKPOINT_INTERVAL = 1000

TARGET_PEPTIDE = "RVKRVWPLVIRTVIAGYNLYRAIKKK"

REWARD_MODELS = ["ACP", "AFP", "AMP", "AVP", "HEM"]

HEM_CONCENTRATION = 50.0  # μg/mL, passed to HEM hemolysis predictor
